import { sql } from '../src/config/database.js';
import dotenv from 'dotenv';

dotenv.config();

const seedSongs = [
  {
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    album: 'A Night at the Opera',
    genre: 'Rock',
    year: 1975,
    duration: 354,
    image_url: 'https://i.pinimg.com/736x/27/97/86/279786b3c4f363e17d55beb4750f9414.jpg',
  },
  {
    title: 'Billie Jean',
    artist: 'Michael Jackson',
    album: 'Thriller',
    genre: 'Pop',
    year: 1982,
    duration: 294,
    image_url: 'https://i.pinimg.com/1200x/d4/ac/6d/d4ac6d55f9b36fba8ced3e4d8d40d6cb.jpg',
  },
  {
    title: 'Smells Like Teen Spirit',
    artist: 'Nirvana',
    album: 'Nevermind',
    genre: 'Grunge',
    year: 1991,
    duration: 301,
    image_url: 'https://i.pinimg.com/736x/52/aa/fa/52aafa63e8276a5560e9168316830edd.jpg',
  },
  {
    title: 'Hotel California',
    artist: 'Eagles',
    album: 'Hotel California',
    genre: 'Rock',
    year: 1976,
    duration: 391,
    image_url: 'https://i.pinimg.com/1200x/0d/b4/c6/0db4c6ef319652746196a0cade896196.jpg',
  },
  {
    title: 'Stairway to Heaven',
    artist: 'Led Zeppelin',
    album: 'Led Zeppelin IV',
    genre: 'Rock',
    year: 1971,
    duration: 482,
    image_url: 'https://i.pinimg.com/736x/6b/ee/1e/6bee1ea44a6ba1e081dd27c99c61cbc0.jpg',
  },
  {
    title: 'Like a Rolling Stone',
    artist: 'Bob Dylan',
    album: 'Highway 61 Revisited',
    genre: 'Folk Rock',
    year: 1965,
    duration: 366,
    image_url: 'https://i.pinimg.com/736x/c2/5f/59/c25f596ee157a703e50b6c17db61b82a.jpg',
  },
  {
    title: 'Imagine',
    artist: 'John Lennon',
    album: 'Imagine',
    genre: 'Pop Rock',
    year: 1971,
    duration: 183,
    image_url: 'https://i.pinimg.com/736x/58/03/8b/58038bec3079c68694ae1f2e2aac6c85.jpg',
  },
  {
    title: 'What a Wonderful World',
    artist: 'Louis Armstrong',
    album: 'What a Wonderful World',
    genre: 'Jazz',
    year: 1967,
    duration: 139,
    image_url: 'https://i.pinimg.com/736x/a0/f8/d8/a0f8d8fe3241ff4d7ba7287754ef217b.jpg',
  },
  {
    title: 'Sweet Child O Mine',
    artist: "Guns N' Roses",
    album: 'Appetite for Destruction',
    genre: 'Rock',
    year: 1987,
    duration: 356,
    image_url: 'https://i.pinimg.com/736x/6a/16/93/6a1693761d56c8abc9e389deeb881554.jpg',
  },
  {
    title: 'Purple Rain',
    artist: 'Prince',
    album: 'Purple Rain',
    genre: 'Pop Rock',
    year: 1984,
    duration: 528,
    image_url: 'https://example.com/purple-rain.jpg',
  },
  {
    title: 'Thunderstruck',
    artist: 'AC/DC',
    album: 'The Razors Edge',
    genre: 'Rock',
    year: 1990,
    duration: 292,
    image_url: 'https://example.com/thunderstruck.jpg',
  },
  {
    title: 'Wonderwall',
    artist: 'Oasis',
    album: "(What's the Story) Morning Glory?",
    genre: 'Britpop',
    year: 1995,
    duration: 258,
    image_url: 'https://example.com/wonderwall.jpg',
  },
  {
    title: 'Creep',
    artist: 'Radiohead',
    album: 'Pablo Honey',
    genre: 'Alternative Rock',
    year: 1992,
    duration: 238,
    image_url: 'https://example.com/creep.jpg',
  },
  {
    title: 'Losing My Religion',
    artist: 'R.E.M.',
    album: 'Out of Time',
    genre: 'Alternative Rock',
    year: 1991,
    duration: 269,
    image_url: 'https://example.com/losing-religion.jpg',
  },
  {
    title: 'Black',
    artist: 'Pearl Jam',
    album: 'Ten',
    genre: 'Grunge',
    year: 1991,
    duration: 343,
    image_url: 'https://example.com/black.jpg',
  },
  {
    title: 'Zombie',
    artist: 'The Cranberries',
    album: 'No Need to Argue',
    genre: 'Alternative Rock',
    year: 1994,
    duration: 312,
    image_url: 'https://example.com/zombie.jpg',
  },
  {
    title: 'Bitter Sweet Symphony',
    artist: 'The Verve',
    album: 'Urban Hymns',
    genre: 'Britpop',
    year: 1997,
    duration: 357,
    image_url: 'https://example.com/bitter-sweet.jpg',
  },
  {
    title: 'Don\'t Stop Believin\'',
    artist: 'Journey',
    album: 'Escape',
    genre: 'Rock',
    year: 1981,
    duration: 251,
    image_url: 'https://example.com/dont-stop.jpg',
  },
  {
    title: 'Livin\' on a Prayer',
    artist: 'Bon Jovi',
    album: 'Slippery When Wet',
    genre: 'Rock',
    year: 1986,
    duration: 249,
    image_url: 'https://example.com/livin-prayer.jpg',
  },
  {
    title: 'Sweet Dreams (Are Made of This)',
    artist: 'Eurythmics',
    album: 'Sweet Dreams (Are Made of This)',
    genre: 'Synth-pop',
    year: 1983,
    duration: 216,
    image_url: 'https://example.com/sweet-dreams.jpg',
  },
  {
    title: 'Take On Me',
    artist: 'a-ha',
    album: 'Hunting High and Low',
    genre: 'Synth-pop',
    year: 1985,
    duration: 225,
    image_url: 'https://example.com/take-on-me.jpg',
  },
  {
    title: 'Every Breath You Take',
    artist: 'The Police',
    album: 'Synchronicity',
    genre: 'New Wave',
    year: 1983,
    duration: 253,
    image_url: 'https://example.com/every-breath.jpg',
  },
  {
    title: 'With or Without You',
    artist: 'U2',
    album: 'The Joshua Tree',
    genre: 'Rock',
    year: 1987,
    duration: 296,
    image_url: 'https://example.com/with-without.jpg',
  },
  {
    title: 'One',
    artist: 'U2',
    album: 'Achtung Baby',
    genre: 'Rock',
    year: 1991,
    duration: 276,
    image_url: 'https://example.com/one.jpg',
  },
  {
    title: 'November Rain',
    artist: "Guns N' Roses",
    album: 'Use Your Illusion I',
    genre: 'Rock',
    year: 1991,
    duration: 537,
    image_url: 'https://example.com/november-rain.jpg',
  },
  {
    title: 'Comfortably Numb',
    artist: 'Pink Floyd',
    album: 'The Wall',
    genre: 'Progressive Rock',
    year: 1979,
    duration: 384,
    image_url: 'https://example.com/comfortably-numb.jpg',
  },
  {
    title: 'Wish You Were Here',
    artist: 'Pink Floyd',
    album: 'Wish You Were Here',
    genre: 'Progressive Rock',
    year: 1975,
    duration: 334,
    image_url: 'https://example.com/wish-you-were.jpg',
  },
  {
    title: 'Money',
    artist: 'Pink Floyd',
    album: 'The Dark Side of the Moon',
    genre: 'Progressive Rock',
    year: 1973,
    duration: 382,
    image_url: 'https://example.com/money.jpg',
  },
  {
    title: 'Another Brick in the Wall',
    artist: 'Pink Floyd',
    album: 'The Wall',
    genre: 'Progressive Rock',
    year: 1979,
    duration: 240,
    image_url: 'https://example.com/another-brick.jpg',
  },
  {
    title: 'Boogie Wonderland',
    artist: 'Earth, Wind & Fire',
    album: 'I Am',
    genre: 'Disco',
    year: 1979,
    duration: 268,
    image_url: 'https://example.com/boogie.jpg',
  },
  {
    title: 'Stayin\' Alive',
    artist: 'Bee Gees',
    album: 'Saturday Night Fever',
    genre: 'Disco',
    year: 1977,
    duration: 229,
    image_url: 'https://example.com/stayin-alive.jpg',
  },
  {
    title: 'Dancing Queen',
    artist: 'ABBA',
    album: 'Arrival',
    genre: 'Pop',
    year: 1976,
    duration: 230,
    image_url: 'https://example.com/dancing-queen.jpg',
  },
  {
    title: 'Mamma Mia',
    artist: 'ABBA',
    album: 'ABBA',
    genre: 'Pop',
    year: 1975,
    duration: 210,
    image_url: 'https://example.com/mamma-mia.jpg',
  },
  {
    title: 'Waterloo',
    artist: 'ABBA',
    album: 'Waterloo',
    genre: 'Pop',
    year: 1974,
    duration: 164,
    image_url: 'https://example.com/waterloo.jpg',
  },
  {
    title: 'I Will Always Love You',
    artist: 'Whitney Houston',
    album: 'The Bodyguard',
    genre: 'R&B',
    year: 1992,
    duration: 273,
    image_url: 'https://example.com/will-always.jpg',
  },
  {
    title: 'My Heart Will Go On',
    artist: 'Celine Dion',
    album: 'Let\'s Talk About Love',
    genre: 'Pop',
    year: 1997,
    duration: 280,
    image_url: 'https://example.com/my-heart.jpg',
  },
  {
    title: 'Total Eclipse of the Heart',
    artist: 'Bonnie Tyler',
    album: 'Faster Than the Speed of Night',
    genre: 'Pop Rock',
    year: 1983,
    duration: 412,
    image_url: 'https://example.com/total-eclipse.jpg',
  },
  {
    title: 'I Want to Know What Love Is',
    artist: 'Foreigner',
    album: 'Agent Provocateur',
    genre: 'Rock',
    year: 1984,
    duration: 300,
    image_url: 'https://example.com/want-to-know.jpg',
  },
  {
    title: 'Careless Whisper',
    artist: 'George Michael',
    album: 'Make It Big',
    genre: 'Pop',
    year: 1984,
    duration: 370,
    image_url: 'https://example.com/careless-whisper.jpg',
  },
  {
    title: 'Faith',
    artist: 'George Michael',
    album: 'Faith',
    genre: 'Pop',
    year: 1987,
    duration: 237,
    image_url: 'https://example.com/faith.jpg',
  },
  {
    title: 'Smooth',
    artist: 'Santana',
    album: 'Supernatural',
    genre: 'Rock',
    year: 1999,
    duration: 296,
    image_url: 'https://example.com/smooth.jpg',
  },
  {
    title: 'Under the Bridge',
    artist: 'Red Hot Chili Peppers',
    album: 'Blood Sugar Sex Magik',
    genre: 'Alternative Rock',
    year: 1991,
    duration: 264,
    image_url: 'https://example.com/under-bridge.jpg',
  },
  {
    title: 'Californication',
    artist: 'Red Hot Chili Peppers',
    album: 'Californication',
    genre: 'Alternative Rock',
    year: 1999,
    duration: 329,
    image_url: 'https://example.com/californication.jpg',
  },
  {
    title: 'Scar Tissue',
    artist: 'Red Hot Chili Peppers',
    album: 'Californication',
    genre: 'Alternative Rock',
    year: 1999,
    duration: 216,
    image_url: 'https://example.com/scar-tissue.jpg',
  },
  {
    title: 'Enter Sandman',
    artist: 'Metallica',
    album: 'Metallica',
    genre: 'Heavy Metal',
    year: 1991,
    duration: 331,
    image_url: 'https://example.com/enter-sandman.jpg',
  },
  {
    title: 'Nothing Else Matters',
    artist: 'Metallica',
    album: 'Metallica',
    genre: 'Heavy Metal',
    year: 1991,
    duration: 388,
    image_url: 'https://example.com/nothing-else.jpg',
  },
  {
    title: 'Master of Puppets',
    artist: 'Metallica',
    album: 'Master of Puppets',
    genre: 'Heavy Metal',
    year: 1986,
    duration: 515,
    image_url: 'https://example.com/master-puppets.jpg',
  },
  {
    title: 'Smoke on the Water',
    artist: 'Deep Purple',
    album: 'Machine Head',
    genre: 'Rock',
    year: 1972,
    duration: 340,
    image_url: 'https://example.com/smoke-water.jpg',
  },
  {
    title: 'Highway to Hell',
    artist: 'AC/DC',
    album: 'Highway to Hell',
    genre: 'Rock',
    year: 1979,
    duration: 208,
    image_url: 'https://example.com/highway-hell.jpg',
  },
  {
    title: 'Back in Black',
    artist: 'AC/DC',
    album: 'Back in Black',
    genre: 'Rock',
    year: 1980,
    duration: 255,
    image_url: 'https://example.com/back-black.jpg',
  },
];

async function seed() {
  try {
    console.log('🌱 Seeding database...');

    for (const song of seedSongs) {
      await sql`
        INSERT INTO songs (title, artist, album, genre, year, duration, image_url)
        VALUES (${song.title}, ${song.artist}, ${song.album}, ${song.genre}, ${song.year}, ${song.duration}, ${song.image_url})
        ON CONFLICT DO NOTHING
      `;
    }

    console.log(`✅ Database seeded successfully with ${seedSongs.length} songs`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed failed:', error);
    process.exit(1);
  }
}

seed();

